server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

spring:
  application:
    name: transactions-api
  jackson:
    deserialization:
      use-big-decimal-for-floats: true

aws:
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:http://localhost:8000}
    region: ${AWS_REGION:us-east-1}
    table-name: TransactionsDB
